### PR TITLE
Add a rotation option

### PR DESCRIPTION
**Pull request by benjaminjkraft**
I personally love rotating party emoji!  This allows passing
`--rotate=1` to make a rotating emoji.

### CODE REVIEW

**Comment by scotchfield** [comment]
This is amazing! Thank you! :D

**Comment by scotchfield** [comment]
You/we might want to add some documentation in the README so this gets some more attention. I laughed pretty hard at "rotating-party-smile". 😂

**Comment by benjaminjkraft** [comment]
I attempted to!  Did it not work right?

**Comment by scotchfield** [comment]
I was too distracted by the fun emoji and didn't even notice, sorry about that! You totally did, and thank you. 😄

**Pull request merged**
